server {
    listen      80;
    server_name aapinstaller;

    location /status {
        add_header Content-Type text/plain;
        return 200 'OK';
    }

    location = /api/status {
        proxy_pass http://127.0.0.1:9090/status;
    }
}
